//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessControl.SDSService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SDSService.SDSServiceSoap")]
    public interface SDSServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetSellInfo(string tid, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetConSignment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SetConSignment(string sellCode, string tid, string Cname, string nickName, string FXRmb, string ZRBM, string Accounts, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MobileLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet MobileLogin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetSellMessage(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckSN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string CheckSN(string SN, string Code, string Scode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSNNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetSNNumber(string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoSendGoods", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet AutoSendGoods(string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoSellFiner", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string AutoSellFiner(string Code, string RealName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoSellSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string AutoSellSend(string Code, string scode, string RealName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void GetSellList(string cname, string scode, string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCheckBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void GetCheckBalance(string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SDSServiceSoapChannel : ProcessControl.SDSService.SDSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SDSServiceSoapClient : System.ServiceModel.ClientBase<ProcessControl.SDSService.SDSServiceSoap>, ProcessControl.SDSService.SDSServiceSoap {
        
        public SDSServiceSoapClient() {
        }
        
        public SDSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SDSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSellInfo(string tid, string token) {
            return base.Channel.GetSellInfo(tid, token);
        }
        
        public string SetConSignment(string sellCode, string tid, string Cname, string nickName, string FXRmb, string ZRBM, string Accounts, string token) {
            return base.Channel.SetConSignment(sellCode, tid, Cname, nickName, FXRmb, ZRBM, Accounts, token);
        }
        
        public System.Data.DataSet MobileLogin(string username, string password) {
            return base.Channel.MobileLogin(username, password);
        }
        
        public System.Data.DataSet GetSellMessage(string code) {
            return base.Channel.GetSellMessage(code);
        }
        
        public string CheckSN(string SN, string Code, string Scode) {
            return base.Channel.CheckSN(SN, Code, Scode);
        }
        
        public System.Data.DataSet GetSNNumber(string Code) {
            return base.Channel.GetSNNumber(Code);
        }
        
        public System.Data.DataSet AutoSendGoods(string Code) {
            return base.Channel.AutoSendGoods(Code);
        }
        
        public string AutoSellFiner(string Code, string RealName) {
            return base.Channel.AutoSellFiner(Code, RealName);
        }
        
        public string AutoSellSend(string Code, string scode, string RealName) {
            return base.Channel.AutoSellSend(Code, scode, RealName);
        }
        
        public void GetSellList(string cname, string scode, string state) {
            base.Channel.GetSellList(cname, scode, state);
        }
        
        public void GetCheckBalance(string code) {
            base.Channel.GetCheckBalance(code);
        }
    }
}
